### ISSUE TITLE
Could you share the `test.sh` script used in the demo?

### ISSUE THREAD

**Issue by lewiscowper** [mathisonian/hyperterm-window#5]
Hi there,

I would like to build some things based on hyperterm-window, and I was wondering whether you could share, either in some docs somewhere/a gist/the repo, whether you could share the `test.sh` script that you call, so that I could get an idea of how that demo works please?

Fantastic project! Really great ✨ 💖 ✨

**Comment by mathisonian** [comment]
Hey @lewiscowper,

I added a more fully fledged example here https://github.com/mathisonian/hyperterm-window/blob/master/examples/index.js that is a bare bones plugin that makes it so running:

```
$ toggle-window
```

will show/hide the window. Please feel free to keep asking questions, it took me a while to wrap my head around how these plugins work. Once that example makes sense, i would check out the source for [hyperchart](https://github.com/mathisonian/hyperchart), to see a little more complex interaction with the command line. 

The example does the following:
- Adds a new `action` called `TOGGLE_WINDOW` that will toggle a flag in the redux state
- Captures the output of the user running `toggle-window` to call that action
- Exposes the `showWindow` variable to the `Term` component.
- Adds a custom decorator to the `Term` component (this is responsible for rendering the window).
